name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run : docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build -t sk-app:latest .
    - name: Tags
      run: |
        docker tag sk-app ${{ secrets.DOCKER_USER }}/sk-app:${{ github.sha }}
        docker tag sk-app ${{ secrets.DOCKER_USER }}/sk-app:latest
    - name: Push to docker hub
      run : |   
        docker push ${{ secrets.DOCKER_USER }}/sk-app:latest
